### ISSUE TITLE
build.xml in both halvade/ and halvade_uploader_tool/ are incorrect

### ISSUE THREAD

**Issue by shirshen12** [ddcap/halvade#2]
Hi Halvade Team,

The build.xml in both halvade/ and halvade_uploader_tool/ are having incorrect src targets. All jars are under the lib/ folder but the build.xml says they are under dist/lib/*.

For example:

In the <target></target> section of halvade build.xml, its as follows:
 `<target name="-post-jar">`
        `<jar jarfile="dist/HalvadeWithLibs.jar">`
            `<zipfileset src="${dist.jar}" excludes="META-INF/*" />`
            `<zipfileset src="dist/lib/commons-cli-1.2.jar" excludes="META-INF/*" />`
            `<zipfileset src="dist/lib/HadoopBam.jar" excludes="META-INF/*" />`
            `<zipfileset src="dist/lib/picard-1.112.jar" excludes="META-INF/*" />`
            `<zipfileset src="dist/lib/sam-1.112.jar" excludes="META-INF/*" />`
            `<zipfileset src="dist/lib/variant-1.112.jar" excludes="META-INF/*" />`
            `<zipfileset src="dist/lib/tribble-1.112.jar" excludes="META-INF/*" />`
            `<manifest>`
                `<attribute name="Main-Class" value="be.ugent.intec.halvade.Halvade"/>`
            `</manifest>`
        `</jar>`
    `</target>`

when it must be:

`<target name="-post-jar">`
        `<jar jarfile="dist/HalvadeWithLibs.jar">`
            `<zipfileset src="${dist.jar}" excludes="META-INF/*" />`
            `<zipfileset src="lib/commons-cli-1.2.jar" excludes="META-INF/*" />`
            `<zipfileset src="lib/HadoopBam.jar" excludes="META-INF/*" />`
            `<zipfileset src="lib/picard-1.112.jar" excludes="META-INF/*" />`
            `<zipfileset src="lib/sam-1.112.jar" excludes="META-INF/*" />`
            `<zipfileset src="lib/variant-1.112.jar" excludes="META-INF/*" />`
            `<zipfileset src="lib/tribble-1.112.jar" excludes="META-INF/*" />`
            `<manifest>`
                `<attribute name="Main-Class" value="be.ugent.intec.halvade.Halvade"/>`
            `</manifest>`
        `</jar>`
    `</target>`

Same exact issue also with HalvadeUploaderTool.

The platform on which we are building:
Fedora 18, 4GB RAM, quad-core Intel CPU

Thanks,

Shirshendu Chakrabarti

**Comment by ddcap** [comment]
Both should work ok, as ant will make a dist/lib/ directory with all corresponding libraries. This build.xml you saw is just a post-jar step, to create a jar file with the libraries included. The step to actually build is in the nbproject/build-impl.xml where the correct libraries are used.

**Comment by shirshen12** [comment]
Ok will test and let you know. Thanks.

**Comment by shirshen12** [comment]
How do I trigger that build file, just hitting ant in the folders picks up the build.xml. Do I need to change the anywhere anything.

**Comment by ddcap** [comment]
The buildfile in the nbprojects directory is called from the build.xml file, so it should work. Which errors are you getting?

**Comment by shirshen12** [comment]
Please check this pastie, the output corresponds to when the I run ant with the original build.xml file. The build fails.
http://pastie.org/private/o7gy69xuvisx681nikzvsq

Please check this pastie, the output corresponds to when the I run ant with the modified build.xml file. The build succeeds.
http://pastie.org/private/qa9xpdcpwmohr0o6fm9wag
The modified build.xml:
http://pastie.org/private/vshel0yh1z3h1pz6nyjzgq

**Comment by ddcap** [comment]
Seems it somehow can't find the commons-cli-1.2.jar file, but for me it finds it. I will change the build file, thanks for letting me know.
