### ISSUE TITLE
Request for RNA-seq pipeline operation guide 

### ISSUE THREAD

**Issue by shirshen12** [ddcap/halvade#4]
Hi Halvade Team,

Can we please have a RNA-seq pipeline guide on the lines of the detailed recipe for operating the DNA-seq pipeline, as seen here: https://github.com/ddcap/halvade/wiki/Recipe:-Running-Halvade-on-a-local-Hadoop-cluster

**Comment by ddcap** [comment]
Yes, I will write down a guide for this, sorry for the delayed response.

**Comment by ddcap** [comment]
@shirshen12 I added a recipe for calling variants with RNA-seq data. Let me know if there are some things that are unclear.
https://github.com/ddcap/halvade/wiki/Recipe:-RNA-seq-with-Halvade-on-a-local-Hadoop-cluster

**Comment by shirshen12** [comment]
Sorry for the late response. Will check and let you know. Was caught up in some work.

**Comment by shirshen12** [comment]
:+1:  Closing this, Its more detailed than the earlier DNA-seq pipeline manual. Thanks!
