### ISSUE TITLE
RNA-seq on distributed mode

### ISSUE THREAD

**Issue by ghost** [ddcap/halvade#8]
Hi,

I'm trying to run RNA pipeline on distributed mode but getting the following error. Can you please share the required settings for distributed mode in case of RNA? Thanks!

**Comment by ddcap** [comment]
Could you please show me the error again, I don't see the error in your comment. The settings should be similar to the DNA pipeline, this page provides more info:
http://halvade.readthedocs.io/en/latest/contents/run.html
Also make sure you have the latest version, the latest versions are now available on a different github page:
https://github.com/biointec/halvade

best,
Dries

**Comment by ghost** [comment]
Hi Dries,

I have opened an issue on https://github.com/biointec/halvade regarding the same with all the exceptions and logs. I tried running RNA-seq on distributed mode with the mentioned settings, but every time it executes, it throws a NULL pointer exception as soon as the first job finishes. Please help in resolving the issue.
